# Generated by Django 4.1 on 2022-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes_bd/')),
            ],
        ),
    ]
